language: c
sudo: false
os:
    - linux
branches:
  only:
    - master

cache:
  directories:
    - $HOME/.elan
    - $TRAVIS_BUILD_DIR/_target

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - export LEAN_VERSION=lean-`lean --run scripts/lean_version.lean`

script:
- leanpkg build